[phases.setup]
nixPkgs = ["python311", "libGL", "libGLU"]

[phases.install]
cmds = []

[phases.build]
cmds = ["python -m pip install --upgrade pip setuptools wheel", "python -m pip install -r requirements.txt"]

[start]
cmd = "python start.py"
