[phases.setup]
nixPkgs = ["libGL", "libGLU", "python311"]
aptPkgs = []

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "python start.py"
